modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "vectorial"
version = "${version}"
displayName = "Vectorial"
description = "SIMD-accelerated SoA entity data layout."
authors = ["uright008"]

[[mixins]]
config = "vectorial.mixins.json"
