modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "redstone"
version = "${version}"
displayName = "Redstone Parallelization"
description = "Parallel redstone update processing for Minecraft servers."
authors = ["uright008"]

[[mixins]]
config = "redstone.mixins.json"
