modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "core"
version = "${version}"
displayName = "Parallel Core"
description = "Central thread pool, world management, and /parallel command system for MC Parallel mods."
authors = ["uright008"]

[[mixins]]
config = "core.mixins.json"
