modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "hopper"
version = "${version}"
displayName = "Hopper Parallelization"
description = "Parallelizes Minecraft hopper logic for improved server TPS."
authors = ["uright008"]

[[mixins]]
config = "hopper.mixins.json"
